### ISSUE TITLE
Some profile modals display incorrectly

### ISSUE THREAD

**Issue by MichaelVasile** [hackrd/staff#2]
Modal content will sometimes be aligned incorrectly. Will add screenshot shortly

**Comment by MrSkee** [comment]
Do you have circumstances or a specific ID that I can try and reproduce the bug with?

**Comment by MichaelVasile** [comment]
@MrSkee it's pretty random. If it happens I will screenshot

**Comment by MrSkee** [comment]
Closed, reopen if you see it happening again.
